### Health Check
GET http://localhost:8080/health
Accept: application/json

### 로그 파일 분석
POST http://localhost:8080/api/v1/logs/analyze
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="loginfo.csv"
Content-Type: text/csv

< ./log_example.csv
--boundary--

###
